### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by megafon929**
Added Russian translation

### CODE REVIEW

**Review by peterfajdiga — CHANGES_REQUESTED** [review]
Hi, thank you very much for the translation! However, I've recently changed some strings, can you please update the translation to the newest version of strings.xml? Thanks again!

**Review by peterfajdiga — APPROVED** [review]
Thank you!

**Comment by peterfajdiga** [comment]
I noticed you're still missing these two:
```
    <string name="action_widget_add">Add a widget</string>
    <string name="action_widget_edit">Edit widget</string>
```
Can you provide the translations for them in a comment here?

**Comment by megafon929** [comment]
<string name="action_widget_add">Добавить виджет</string>
    <string name="action_widget_edit">Изменить виджет</string>

**Comment by peterfajdiga** [comment]
Thank you, I've added them now.

**Pull request merged**
